apiVersion: v1
kind: PersistentVolume
metadata:
  name: job-seekr-pv

spec:
  capacity:
    storage: 2Gi

  accessModes:
    - ReadWriteMany

  storageClassName: manual

  persistentVolumeReclaimPolicy: Retain

  nfs:
    server: 10.0.1.200
    path: /primaryPool/apps/job-seekr


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: job-seekr-pvc
  namespace: job-seekr

spec:
  storageClassName: manual

  accessModes:
    - ReadWriteMany

  resources:
    requests:
      storage: 2Gi

  volumeName: job-seekr-pv

