apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cluster-stress
  namespace: stress

spec:
  selector:
    matchLabels:
      app: cluster-stress

  template:
    metadata:
      labels:
        app: cluster-stress

    spec:
      priorityClassName: background-compute

      containers:
        - name: stress
          image: polinux/stress-ng:latest

          args:
            - "--cpu"
            - "0"
            - "--vm"
            - "2"
            - "--vm-bytes"
            - "75%"
            - "--vm-keep"
            - "--timeout"
            - "0"

          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"

            limits:
              memory: "4Gi"
              # intentionally NO CPU limit → full node saturation when idle
