apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: job-seekr
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: job-seekr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:8
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: job-seekr-db
              mountPath: /data/db
              subPath: mongodb
      volumes:
        - name: job-seekr-db
          persistentVolumeClaim:
            claimName: job-seekr-pvc




