services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    network_mode: host
    command: >
      redis-server
      --bind 0.0.0.0
      --port 6379
      --appendonly yes
      --protected-mode no

      --appendfsync everysec
      --auto-aof-rewrite-percentage 25
      --auto-aof-rewrite-min-size 32mb 
      --dir /data
    
      --maxmemory 512mb
      --maxmemory-policy noeviction
      --save 900 1
      --save 300 10
      --save 60 10000





    volumes:
    - /mnt/raid/redis:/data

  sentinel:
    image: redis:7-alpine
    container_name: sentinel
    restart: unless-stopped
    network_mode: host
    depends_on:
      - redis
    command: >
      sh -c '
      cat > /tmp/sentinel.conf <<EOF
      port 26379
      bind 0.0.0.0
      sentinel monitor mymaster 10.0.1.3 6379 2
      sentinel down-after-milliseconds mymaster 5000
      sentinel failover-timeout mymaster 10000
      sentinel parallel-syncs mymaster 1
      EOF
      redis-sentinel /tmp/sentinel.conf
      '
