apiVersion: v1
kind: Service
metadata:
  annotations:
    kube-vip.io/loadbalancerIPs: 10.0.1.100
    kube-vip.io/vipHost: node-2
    meta.helm.sh/release-name: traefik
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2026-01-20T22:08:39Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-37.1.1_up37.1.0
  name: traefik
  namespace: kube-system
  resourceVersion: "48414251"
  uid: cb78c407-0074-48ce-a8b6-521d2862eb59
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.43.173.44
  clusterIPs:
  - 10.43.173.44
  externalIPs:
  - 10.0.1.100
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: PreferDualStack
  ports:
  - name: web
    nodePort: 31909
    port: 80
    protocol: TCP
    targetPort: web
  - name: websecure
    nodePort: 31855
    port: 443
    protocol: TCP
    targetPort: websecure
  selector:
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/name: traefik
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 10.0.1.1
      ipMode: VIP
    - ip: 10.0.1.2
      ipMode: VIP
    - ip: 10.0.1.3
      ipMode: VIP

