apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: juicefs-sc
provisioner: csi.juicefs.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  # CSI secrets
  csi.storage.k8s.io/node-publish-secret-name: juicefs-s3
  csi.storage.k8s.io/node-publish-secret-namespace: kube-system
  csi.storage.k8s.io/provisioner-secret-name: juicefs-s3
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system

  # JuiceFS configuration
  name: "juicefs"
  metaurl: "redis://10.0.1.1:6379,10.0.1.2:6379,10.0.1.3:6379/0"
  storage: "s3"
  bucket: "http://NODE_IP:9000/juicefs"
