apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-worker
  namespace: job-seekr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-worker
  template:
    metadata:
      labels:
        app: email-worker
    spec:
      containers:
        - name: email-worker
          image: ghcr.io/jensen-lloyd/job-seekr/email-worker:dev
          imagePullPolicy: Always
