apiVersion: apps/v1
kind: DaemonSet

metadata:
  name: foldingathome
  namespace: folding

spec:
  selector:
    matchLabels:
      app: foldingathome

  template:
    metadata:
      labels:
        app: foldingathome

    spec:
      priorityClassName: background-compute

      containers:
        - name: fah
          image: linuxserver/foldingathome:latest

          env:
            - name: USER
              value: Jensen

            - name: TOKEN
              value: YN0IzYN0j6cOmj6cq6wvHq6wq2fATq2eVgI0sVgIq9M

            - name: TEAM
              value: "0"

            - name: ENABLE_GPU
              value: "false"

            - name: TZ
              value: Australia/Melbourne

            - name: PUID
              value: "1000"

            - name: PGID
              value: "1000"

            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"

            limits:
              cpu: "4"
              memory: "8Gi"

          volumeMounts:
            - name: folding-data
              mountPath: /config
              subPathExpr: $(NODE_NAME)

      volumes:
        - name: folding-data
          hostPath:
            path: /mnt/juicefs/folding
            type: DirectoryOrCreate
