apiVersion: apps/v1
kind: Deployment
metadata:
  name: focus-board
  namespace: focus-board
spec:
  replicas: 1
  selector:
    matchLabels:
      app: focus-board
  template:
    metadata:
      labels:
        app: focus-board
    spec:
      containers:
        - name: focus-board
          image: ghcr.io/jensen-lloyd/focus-board/focus-board:dev
          imagePullPolicy: Always


          env:


          volumeMounts:
            - name: focus-board-storage
              mountPath: /data

          ports:
            - containerPort: 8080


          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

      volumes:
        - name: focus-board-storage
          persistentVolumeClaim:
            claimName: focus-board-pvc

