apiVersion: v1 
kind: Service 
metadata: 
  name: focus-board
  namespace: focus-board
spec: 
  selector: 
    app: focus-board
  ports: 
    - port: 80
      targetPort: 8080
  type: ClusterIP 
--- 
apiVersion: networking.k8s.io/v1 
kind: Ingress 
metadata: 
  name: focus-board
  namespace: focus-board
  annotations: 
    spec.ingressClassName: traefik 
spec: 
  rules: 
  - host: focus-board.colins.io
    http: 
      paths: 
        - path: / 
          pathType: Prefix 
          backend: 
            service: 
              name: focus-board
              port: 
                number: 80
  tls: 
    - hosts: 
      - focus-board.colins.io 
