apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-console
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio-console
  template:
    metadata:
      labels:
        app: minio-console
    spec:
      containers:
        - name: console
          image: ghcr.io/georgmangold/console:latest
          imagePullPolicy: Always


          ports:
            - containerPort: 9090
              protocol: TCP

          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: CONSOLE_MINIO_SERVER
              value: "http://$(NODE_IP):9000"

---
apiVersion: v1
kind: Service
metadata:
  name: minio-console
  namespace: default
spec:
  type: NodePort
  selector:
    app: minio-console
  ports:
    - port: 9090        # container port
      targetPort: 9090  # internal container port
      nodePort: 30090   # access on nodeIP:30090

